import { Project, TaskList } from "@/app/types";
// import * as constants from "./constants";

export const projects: Project[] = [
  {
    id: "1",
    title: "Project 1",
    description: "Description 1",
    startDate: "2024-05-01",
    deadline: "2024-05-31",
    status: "pending",
  },
  {
    id: "2",
    title: "Project 2",
    description: "Description 2",
    status: "active",
    startDate: "2024-05-25",
    deadline: "2024-05-31",
  },
];

export const resources = [
  {
    id: "1",
    projectId: "2",
    userId: "2",
    title: "web.dev html text tutorial",
    link: "https://web.dev/learn/html",
    description:
      "This is an article that allows me learn how to markup text in html properly.",
  },
  {
    id: "2",
    projectId: "2",
    userId: "2",
    title: "freecodecamp how to start coding",
    link: "https://freecodecamp.org",
    description:
      "An artiel from free code camp on how to start coding right now. Really has some great points I should note down",
  },
  {
    id: "3",
    projectId: "2",
    userId: "2",
    title: "Mdn css tutorial on flexbox",
    link: "https://developer.mozilla.org/",
    description:
      "Official tutorial from mozilla themselves on CSS. Covers helpful concepts and parts of CSS like flexbox, grid and alot of other modern css features like has() and so on",
  },
];

export const taskLists: TaskList[] = [
  {
    id: "1",
    title: "Todos for V1",
    status: "active",
    taskItems: [
      {
        id: "232",
        title: "Build custom select component",
        tags: [],
        deadline: new Date("2024-05-31"),
        description: "",
        estimatedCompletionTime: "",
        priority: "mid",
        status: "paused",
        startDate: null,
        taggedResources: [],
      },
      {
        id: "23003",
        title: "Integrate custom select component into codebase",
        tags: [],
        deadline: new Date("2024-05-31"),
        description: "",
        estimatedCompletionTime: "",
        priority: "high",
        status: "active",
        startDate: null,
        taggedResources: [],
      },
    ],
  },
  {
    id: "2",
    title: "Feature requests",
    status: "pending",
    taskItems: [
      {
        id: "232",
        title: "Build custom select component",
        tags: [],
        deadline: new Date("2024-05-31"),
        description: "",
        estimatedCompletionTime: "",
        priority: "mid",
        status: "paused",
        startDate: null,
        taggedResources: [],
      },
      {
        id: "23003",
        title: "Integrate custom select component into codebase",
        tags: [],
        deadline: new Date("2024-05-31"),
        description: "",
        estimatedCompletionTime: "",
        priority: "high",
        status: "pending",
        startDate: null,
        taggedResources: [],
      },
      {
        id: "22939",
        title: "Integrate custom select component into codebase",
        tags: [],
        deadline: new Date("2024-05-31"),
        description: "",
        estimatedCompletionTime: "",
        priority: "high",
        status: "pending",
        startDate: null,
        taggedResources: [],
      },
      {
        id: "20282",
        title: "Integrate custom select component into codebase",
        tags: [],
        deadline: new Date("2024-05-31"),
        description: "",
        estimatedCompletionTime: "",
        priority: "high",
        status: "pending",
        startDate: null,
        taggedResources: [],
      },

      {
        id: "29s02",
        title: "Integrate custom select component into codebase",
        tags: [],
        deadline: new Date("2024-05-31"),
        description: "",
        estimatedCompletionTime: "",
        priority: "high",
        status: "pending",
        startDate: null,
        taggedResources: [],
      },
      {
        id: "lwlwlw9w0",
        title: "Integrate custom select component into codebase",
        tags: [],
        deadline: new Date("2024-05-31"),
        description: "",
        estimatedCompletionTime: "",
        priority: "high",
        status: "pending",
        startDate: null,
        taggedResources: [],
      },
      {
        id: "29022",
        title: "Build custom select component",
        tags: [],
        deadline: new Date("2024-05-31"),
        description: "",
        estimatedCompletionTime: "",
        priority: "mid",
        status: "paused",
        startDate: null,
        taggedResources: [],
      },
    ],
  },
  ,
];
